title: "Rishabh Singh"
author: "Rishabh Singh"
description: "University of Florida"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home", icon: home}
  - {file: "research.md", title: "Research"}:
     - {file: "Model_unc.md", title: "Model Uncertainty"}
  - {file: "publications.md", title: "Publications"}
  - {file: "talks.md", title: "Talks"}
  - {file: "industry.md", title: "Industry"}
  - {url: "/rish.pdf", title: "CV"}
  - {url: "/Rishabh_bio.pdf", title: "Bio"}
  - {file: "undergraduate.md", title: "Undergraduate"}
  - {file: "service.md", title: "Service"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rish283@ufl.edu"}
  - {title: Github, icon: github, url: "https://github.com/rish283"}
  - {title: linkedin, icon: linkedin, url: "https://www.linkedin.com/in/rishabh270"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/rish283"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
